### ISSUE TITLE
PublishParentFolderTrigger example here didn't work for me in Cascade 8.3

### ISSUE THREAD

**Issue by tamhscwebteam** [hannonhill/Cascade-Server-Workflow#1]
Tried using this workflow and it wasn't functioning for me. Narrowed it down to a problem with [PublishParentFolder (starting line 76)](https://github.com/hannonhill/Cascade-Server-Workflow/blob/master/Approval/approval-with-staging-publish.xml#L76). 

After discussing with Ryan Griffith in HH support, he said documentation on the [Publish Parent Folder trigger](https://www.hannonhill.com/kb/Workflow-Trigger/available-workflow-triggers/publish-parent-folder-trigger.html) doesn't mention this directly, but in order for the trigger to work, you must specify AT LEAST one destination parameter so the trigger knows where it should publish to.

Though trial and error, I also discovered that if you have multiple destinations separated by a comma, there can’t be a space after the comma. Don't think I've found that in any documentation so adding here for anyone Googling for help in the future.

**Example:** 

```xml
     <trigger name="PublishParentFolderTrigger" >
          <parameter>
               <name>authorizing-type</name>
               <value>system</value>
          </parameter>
          <parameter>
               <name>destination</name>
               <value>/test.mysite.edu,/mysite.edu</value>
          </parameter>
     </trigger>
```

[https://github.com/hannonhill/Cascade-Server-Workflow/blob/master/Approval/approval-with-staging-publish.xml#L76](https://github.com/hannonhill/Cascade-Server-Workflow/blob/master/Approval/approval-with-staging-publish.xml#L76)

**Comment by rgriffith** [comment]
Thank you for reporting this, @tamhscwebteam. I went ahead and adjusted the usage of the trigger to include the `destination` parameter (3770871).
